services:
  setup-proxy:
    image: nixery.dev/dash/gettext
    working_dir: /work
    command:
      dash -c "envsubst < traefik.yml.tpl > traefik.yml"
    environment:
      - INFRA_ACME_EMAIL
      - INFRA_BASE_DOMAIN
    volumes:
      - ./traefik:/work:rw

  proxy:
    image: traefik:v3.6
    depends_on:
      setup-proxy:
        condition: service_completed_successfully
    ports:
      - "0.0.0.0:443:443"
    volumes:
      - certs:/certs:rw
      - ./traefik:/etc/traefik:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      default:
      ingress:
    restart: unless-stopped

  db:
    image: postgres:18-alpine
    shm_size: 128mb
    environment:
      POSTGRES_PASSWORD: ${INFRA_POSTGRES_PASS}
    volumes:
      - db:/var/lib/postgresql:rw
    networks:
      internal:
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "postgres", "-d", "postgres"]
      interval: 1m
      start_period: 30s
      start_interval: 5s
    restart: unless-stopped

  pg-label:
    image: localhost/pg-label
    depends_on:
      db:
        condition: service_healthy
        restart: true
    environment:
      PGUSER: postgres
      PGHOST: db.internal
      PGPASSWORD: ${INFRA_POSTGRES_PASS}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      internal:
    restart: unless-stopped

volumes:
  db:
  certs:

networks:
  ingress:
    name: ingress
    internal: true
    #driver: ipvlan
  internal:
    name: internal
    internal: true
    driver: ipvlan
